### ISSUE TITLE
v2.0

### ISSUE THREAD

**Issue by pacMakaveli** [studio51/fluent-icons#6]
### TODO

- [x] Add React library
- [x] Ensure JSON output is minimal
- [x] Improve Performance
- [x] Improve Caching

### Fix

- [x] The current caching mechanism causes an issue where the icons are not visible on the first page load. On subsequent page loads the icons are fine and cache, but that initial page load affects UX.

### Wishlist

- [ ] Add github actions to check new icons daily
- [ ] Create weekly releases using github actions
